# Generated by Django 5.1.7 on 2025-04-08 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('details', models.TextField()),
                ('reviwer_name', models.CharField(default='Traveler', max_length=100)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_img', models.ImageField(upload_to='review_pic')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
