# Generated by Django 5.1.7 on 2025-04-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_review_alter_package_caption_alter_package_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviwer_name',
            new_name='reviewer_name',
        ),
    ]
