# Generated by Django 5.2 on 2025-04-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0007_rename_location_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
    ]
