# Generated by Django 5.2 on 2025-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0008_rename_name_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='division',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
