# Generated by Django 5.2 on 2025-04-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0009_location_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.division'),
        ),
    ]
