# Generated by Django 5.2 on 2025-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0013_remove_review_reviewer_name_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
