# Generated by Django 5.2 on 2025-04-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0014_review_reviewer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='cost_by_bus',
            field=models.IntegerField(default=0, help_text='Estimated cost by bus (৳)'),
        ),
        migrations.AddField(
            model_name='location',
            name='cost_by_plane',
            field=models.IntegerField(default=0, help_text='Estimated cost by plane (৳)'),
        ),
        migrations.AddField(
            model_name='location',
            name='cost_by_train',
            field=models.IntegerField(default=0, help_text='Estimated cost by train (৳)'),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('feature', 'Feature'), ('historical', 'Historical'), ('none', 'None')], default='none', help_text='Label this location as Featured, Historical, or None', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestApp.location_type'),
        ),
    ]
